# Generated by Django 4.2 on 2024-06-12 17:42

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 12, 17, 42, 20, 709846, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Время",
            ),
        ),
    ]
